export const ADD_FLASH_MESSAGE = 'ADD_FLASH_MESSAGE';
export const DELETE_FLASH_MESSAGE = 'DELETE_FLASH_MESSAGE';
// export const USER_LOGGED_IN = 'USER_LOGGED_IN';
// export const USER_LOGGED_OUT = 'USER_LOGGED_OUT';
// export const USER_FETCHED = 'USER_FETCHED';
// export const LOCALE_SET = 'LOCALE_SET';
